import random

# Word bank with emoji hints (100+ words)
WORD_BANK = [
    # Compound words (can be typed with or without spaces)
    {"word": "supermarket", "emoji": "🦸 + 🏪", "aliases": ["super market", "supermarket"]},
    {"word": "sunflower", "emoji": "☀️ + 🌻", "aliases": ["sun flower", "sunflower"]},
    {"word": "watermelon", "emoji": "💧 + 🍈", "aliases": ["water melon", "watermelon"]},
    {"word": "pineapple", "emoji": "🌲 + 🍎", "aliases": ["pine apple", "pineapple"]},
    {"word": "strawberry", "emoji": "🥤 + 🫐", "aliases": ["straw berry", "strawberry"]},
    {"word": "blueberry", "emoji": "🔵 + 🫐", "aliases": ["blue berry", "blueberry"]},
    {"word": "dragonfruit", "emoji": "🐉 + 🍎", "aliases": ["dragon fruit", "dragonfruit"]},
    {"word": "cupcake", "emoji": "🥤 + 🎂", "aliases": ["cup cake", "cupcake"]},
    {"word": "pancake", "emoji": "🍳 + 🎂", "aliases": ["pan cake", "pancake"]},
    {"word": "cheesecake", "emoji": "🧀 + 🎂", "aliases": ["cheese cake", "cheesecake"]},
    {"word": "milkshake", "emoji": "🥛 + 🤝", "aliases": ["milk shake", "milkshake"]},
    {"word": "hotdog", "emoji": "🔥 + 🐕", "aliases": ["hot dog", "hotdog"]},
    {"word": "meatball", "emoji": "🥩 + ⚽", "aliases": ["meat ball", "meatball"]},
    {"word": "eggplant", "emoji": "🥚 + 🌱", "aliases": ["egg plant", "eggplant"]},
    {"word": "mushroom", "emoji": "🍄 + 🏠", "aliases": ["mush room", "mushroom"]},
    {"word": "popcorn", "emoji": "🍿 + 🌽", "aliases": ["pop corn", "popcorn"]},
    
    # Superheroes
    {"word": "spiderman", "emoji": "🕷️ + 👨", "aliases": ["spider man", "spiderman"]},
    {"word": "batman", "emoji": "🦇 + 👨", "aliases": ["bat man", "batman"]},
    {"word": "superman", "emoji": "🦸 + 💪", "aliases": ["super man", "superman"]},
    {"word": "ironman", "emoji": "🔩 + 👨", "aliases": ["iron man", "ironman"]},
    
    # Animals
    {"word": "penguin", "emoji": "🐧 + ❄️", "aliases": ["penguin"]},
    {"word": "dolphin", "emoji": "🐬 + 🌊", "aliases": ["dolphin"]},
    {"word": "elephant", "emoji": "🐘 + 🎺", "aliases": ["elephant"]},
    {"word": "dragon", "emoji": "🐉 + 🔥", "aliases": ["dragon"]},
    {"word": "dinosaur", "emoji": "🦖 + 🦴", "aliases": ["dinosaur"]},
    {"word": "butterfly", "emoji": "🧈 + ✈️", "aliases": ["butter fly", "butterfly"]},
    {"word": "ladybug", "emoji": "👩 + 🐛", "aliases": ["lady bug", "ladybug"]},
    {"word": "jellyfish", "emoji": "🍮 + 🐟", "aliases": ["jelly fish", "jellyfish"]},
    {"word": "starfish", "emoji": "⭐ + 🐟", "aliases": ["star fish", "starfish"]},
    {"word": "seahorse", "emoji": "🌊 + 🐴", "aliases": ["sea horse", "seahorse"]},
    {"word": "hedgehog", "emoji": "🌿 + 🐷", "aliases": ["hedge hog", "hedgehog"]},
    {"word": "goldfish", "emoji": "🥇 + 🐟", "aliases": ["gold fish", "goldfish"]},
    {"word": "zebra", "emoji": "🦓 + 🏁", "aliases": ["zebra"]},
    {"word": "peacock", "emoji": "🟢 + 🐓", "aliases": ["pea cock", "peacock"]},
    {"word": "snail", "emoji": "🐌 + 🏠", "aliases": ["snail"]},
    {"word": "turtle", "emoji": "🐢 + 🏃", "aliases": ["turtle"]},
    {"word": "parrot", "emoji": "🦜 + 🗣️", "aliases": ["parrot"]},
    {"word": "catfish", "emoji": "🐱 + 🐟", "aliases": ["cat fish", "catfish"]},
    
    # Professions
    {"word": "firefighter", "emoji": "🔥 + 👨‍🚒", "aliases": ["fire fighter", "firefighter"]},
    {"word": "astronaut", "emoji": "👨‍🚀 + 🌕", "aliases": ["astronaut"]},
    {"word": "detective", "emoji": "🕵️ + 🔍", "aliases": ["detective"]},
    {"word": "cowboy", "emoji": "🐄 + 👦", "aliases": ["cow boy", "cowboy"]},
    {"word": "lifeguard", "emoji": "🛟 + 👮", "aliases": ["life guard", "lifeguard"]},
    {"word": "mailman", "emoji": "📧 + 👨", "aliases": ["mail man", "mailman"]},
    {"word": "teacher", "emoji": "👩‍🏫 + 📚", "aliases": ["teacher"]},
    {"word": "doctor", "emoji": "👨‍⚕️ + 💊", "aliases": ["doctor"]},
    {"word": "pilot", "emoji": "👨‍✈️ + ✈️", "aliases": ["pilot"]},
    {"word": "fisherman", "emoji": "🎣 + 👨", "aliases": ["fisher man", "fisherman"]},
    {"word": "gardener", "emoji": "🌻 + 👨‍🌾", "aliases": ["gardener"]},
    {"word": "painter", "emoji": "👨‍🎨 + 🖌️", "aliases": ["painter"]},
    {"word": "singer", "emoji": "🎤 + 🎵", "aliases": ["singer"]},
    
    # Objects
    {"word": "diamond", "emoji": "💎 + 💍", "aliases": ["diamond"]},
    {"word": "rocket", "emoji": "🚀 + 🌌", "aliases": ["rocket"]},
    {"word": "camera", "emoji": "📸 + 📷", "aliases": ["camera"]},
    {"word": "guitar", "emoji": "🎸 + 🎶", "aliases": ["guitar"]},
    {"word": "football", "emoji": "⚽ + 🥅", "aliases": ["foot ball", "football"]},
    {"word": "basketball", "emoji": "🧺 + ⚽", "aliases": ["basket ball", "basketball"]},
    {"word": "snowman", "emoji": "❄️ + 👨", "aliases": ["snow man", "snowman"]},
    {"word": "raincoat", "emoji": "🌧️ + 🧥", "aliases": ["rain coat", "raincoat"]},
    {"word": "sunglasses", "emoji": "☀️ + 👓", "aliases": ["sun glasses", "sunglasses"]},
    {"word": "toothbrush", "emoji": "🦷 + 🧹", "aliases": ["tooth brush", "toothbrush"]},
    {"word": "hairbrush", "emoji": "💇 + 🧹", "aliases": ["hair brush", "hairbrush"]},
    {"word": "keyboard", "emoji": "🔑 + 📋", "aliases": ["key board", "keyboard"]},
    {"word": "notebook", "emoji": "🚫 + 📚", "aliases": ["note book", "notebook"]},
    {"word": "handbag", "emoji": "✋ + 🎒", "aliases": ["hand bag", "handbag"]},
    {"word": "earring", "emoji": "👂 + 💍", "aliases": ["ear ring", "earring"]},
    {"word": "spaceship", "emoji": "🌌 + 🚢", "aliases": ["space ship", "spaceship"]},
    {"word": "motorcycle", "emoji": "🔧 + 🚲", "aliases": ["motor cycle", "motorcycle"]},
    {"word": "submarine", "emoji": "🥪 + 🌊", "aliases": ["sub marine", "submarine"]},
    {"word": "helicopter", "emoji": "🚁 + 🚓", "aliases": ["helicopter"]},
    {"word": "laptop", "emoji": "🦵 + 🔝", "aliases": ["lap top", "laptop"]},
    
    # Nature
    {"word": "thunderstorm", "emoji": "⛈️ + ⚡", "aliases": ["thunder storm", "thunderstorm"]},
    {"word": "earthquake", "emoji": "🌍 + 🫨", "aliases": ["earth quake", "earthquake"]},
    {"word": "snowflake", "emoji": "❄️ + 🍂", "aliases": ["snow flake", "snowflake"]},
    {"word": "rainbow", "emoji": "🌧️ + 🌈", "aliases": ["rain bow", "rainbow"]},
    {"word": "waterfall", "emoji": "💧 + 🍂", "aliases": ["water fall", "waterfall"]},
    {"word": "volcano", "emoji": "🌋 + 🔥", "aliases": ["volcano"]},
    {"word": "tornado", "emoji": "🌪️ + 💨", "aliases": ["tornado"]},
    {"word": "sunrise", "emoji": "☀️ + ⬆️", "aliases": ["sun rise", "sunrise"]},
    {"word": "sunset", "emoji": "☀️ + ⬇️", "aliases": ["sun set", "sunset"]},
    {"word": "moonlight", "emoji": "🌙 + 💡", "aliases": ["moon light", "moonlight"]},
    
    # Places
    {"word": "castle", "emoji": "🏰 + 👑", "aliases": ["castle"]},
    {"word": "lighthouse", "emoji": "💡 + 🏠", "aliases": ["light house", "lighthouse"]},
    {"word": "airport", "emoji": "✈️ + 🅿️", "aliases": ["air port", "airport"]},
    {"word": "bookstore", "emoji": "📚 + 🏪", "aliases": ["book store", "bookstore"]},
    {"word": "greenhouse", "emoji": "🟢 + 🏠", "aliases": ["green house", "greenhouse"]},
    {"word": "skyscraper", "emoji": "☁️ + 🏢", "aliases": ["sky scraper", "skyscraper"]},
    {"word": "playground", "emoji": "🎮 + 🏟️", "aliases": ["play ground", "playground"]},
    {"word": "bedroom", "emoji": "🛏️ + 🏠", "aliases": ["bed room", "bedroom"]},
    {"word": "bathroom", "emoji": "🛁 + 🏠", "aliases": ["bath room", "bathroom"]},
    {"word": "classroom", "emoji": "📖 + 🏠", "aliases": ["class room", "classroom"]},
    {"word": "graveyard", "emoji": "🪦 + ⚰️", "aliases": ["grave yard", "graveyard"]},
    
    # Misc
    {"word": "password", "emoji": "🔑 + 🗣️", "aliases": ["pass word", "password"]},
    {"word": "fireworks", "emoji": "🔥 + ⚒️", "aliases": ["fire works", "fireworks"]},
    {"word": "earphone", "emoji": "👂 + 📱", "aliases": ["ear phone", "earphone"]},
    {"word": "headphone", "emoji": "🗣️ + 📱", "aliases": ["head phone", "headphone"]},
    {"word": "daydream", "emoji": "📅 + 💭", "aliases": ["day dream", "daydream"]},
    {"word": "nightmare", "emoji": "🌃 + 🐴", "aliases": ["night mare", "nightmare"]},
    {"word": "honeymoon", "emoji": "🍯 + 🌙", "aliases": ["honey moon", "honeymoon"]},
    {"word": "honeycomb", "emoji": "🍯 + 🪮", "aliases": ["honey comb", "honeycomb"]},
    {"word": "tumor", "emoji": "🫵 + ⚰️", "aliases": ["tumor", "tumour"]},
    {"word": "pizza", "emoji": "🍕 + 🧀", "aliases": ["pizza"]},
    {"word": "hamburger", "emoji": "🍔 + 🥩", "aliases": ["hamburger", "ham burger"]},
    {"word": "sandwich", "emoji": "🏖️ + 🧙", "aliases": ["sandwich", "sand wich"]},
    {"word": "sushi", "emoji": "🍣 + 🍚", "aliases": ["sushi"]},
    {"word": "chocolate", "emoji": "🍫 + 🍬", "aliases": ["chocolate"]},
    {"word": "computer", "emoji": "💻 + 🖥️", "aliases": ["computer"]},
    {"word": "robot", "emoji": "🤖 + ⚙️", "aliases": ["robot"]},
    {"word": "alien", "emoji": "👽 + 🛸", "aliases": ["alien"]},
    {"word": "ghost", "emoji": "👻 + 🏚️", "aliases": ["ghost"]},
    {"word": "vampire", "emoji": "🧛 + 🩸", "aliases": ["vampire"]},
    {"word": "zombie", "emoji": "🧟 + 🧠", "aliases": ["zombie"]},
    {"word": "pirate", "emoji": "🏴‍☠️ + 🦜", "aliases": ["pirate"]},
    {"word": "ninja", "emoji": "🥷 + 🗡️", "aliases": ["ninja"]},
    {"word": "samurai", "emoji": "⚔️ + 👘", "aliases": ["samurai"]},
    {"word": "wizard", "emoji": "🧙 + 🪄", "aliases": ["wizard"]},
    {"word": "fairy", "emoji": "🧚 + ✨", "aliases": ["fairy"]},
    {"word": "clown", "emoji": "🤡 + 🎈", "aliases": ["clown"]},
    {"word": "phoenix", "emoji": "🐦‍🔥 + 🔥", "aliases": ["phoenix"]},
]

def get_random_word(exclude_words=None):
    """Get a random word, optionally excluding certain words"""
    available = WORD_BANK.copy()
    if exclude_words:
        available = [w for w in available if w["word"] not in exclude_words]
    return random.choice(available)